# docker-compose.yml
version: '3.8'

services:
  web:
    build: .
    command: python -m uvicorn api:app --host 0.0.0.0 --port 8000 --reload --log-level error
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DB_USERNAME=admin
      - DB_PASSWORD=pinpinpin
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=formula_db
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:8000/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pinpinpin
      - POSTGRES_DB=formula_db
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d formula_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: